### ISSUE TITLE
are there situations where focus-trap wouldn't trap focus?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/ember-focus-trap#19]
The issue I'm having right now is that I've placed focus-trap on a containing modal div, and I'm still able to `shift+tab` focus behind the modal onto the page's non-modal elements.

**Comment by NullVoxPopuli** [comment]
oh actually, I just saw this in the console:
```
Error: Your focus-trap needs to have at least one focusable element
```

but I'm still confused, because when the modal opens this is present and focused (an input): 
![image](https://user-images.githubusercontent.com/199018/78741674-f3d92080-7927-11ea-9eff-18752f5d650a.png)

**Comment by NullVoxPopuli** [comment]
oh wait! duh. my modals are always rendered, and it's the isActive state that changes. oof

**Comment by josemarluedke** [comment]
Yep, you need to have a focusable element in your modal. It can be the modal itself.

I have recently implemented a modal in a component library, you can check that out to have some ideas:

Implementation: https://github.com/josemarluedke/frontile/pull/56
Demo: https://frontile.dev/versions/master/docs/overlays/usage

**Comment by NullVoxPopuli** [comment]
it works! thanks!

all I had to do was set `isActive` to be the `@isActive` of my modal :D
