### ISSUE TITLE
🐛 Redundant code for return focus node

### ISSUE THREAD

**Issue by far-fetched** [josemarluedke/ember-focus-trap#40]
Hey,
during going through code, I found something which I think might be a bug. As `focus-trap` already support set focus for last active element before trap activation ([link](https://github.com/focus-trap/focus-trap/blob/master/index.js#L257)), because of that, I think that some code in modifier is not needed, what is more sometimes it can cause a problem.
### What is wrong
Imagine that I provided a `setReturnFocus` parameter as a function, so it fires on deactivation, and in that function I return my `own-node` which I want to focus. Looking at this [code](https://github.com/josemarluedke/ember-focus-trap/blob/main/addon/modifiers/focus-trap.js#L114): first `focus-trap` focuses `my-own` node, but a few lines later modifier will focus another node which can be different. 
Do I miss something ? Or just this code can be removed and let's delegate setting focus to `focus-trap` itself.

@josemarluedke Could you shed some light on my issue ? If indeed you think this code is not necessary anymore, I can bake a PR for it

**Comment by josemarluedke** [comment]
Hey @far-fetched! 

You are totally correct. I have removed that code in the PR #47. 

Thanks for pointing that out.
