### ISSUE TITLE
v0.8.0 is breaking

### ISSUE THREAD

**Issue by jherdman** [josemarluedke/ember-focus-trap#45]
I know this has been stated in the changelog, but due to the version number anyone using fairly standard practice of pinning with `^` will pick up this version and possibly suffer app breakage.

**Comment by vjonesmuth** [comment]
I'm seeing the following error once upgraded to v0.8.0
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/babel-plugin-cache-busting.js' is not defined by "exports" in .../node_modules/ember-focus-trap/node_modules/@embroider/shared-internals/package.json
```

**Comment by josemarluedke** [comment]
Version v1.0.0 is now released, it should solve the problem with pinning the version down. As for the `ERR_PACKAGE_PATH_NOT_EXPORTED ` related comment, I'm not sure if that is related to this addon at all as it is coming from embroider.

Closing this, let me know if you still encounter problems.
