### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by betocantu93** [josemarluedke/ember-focus-trap#57]
Hello!

I've been trying to upgrade `ember-eui` to 4.x and I'm having trouble with this addon.

using version 0.8.0 I get an error message about modifierManager `capabilities`. Not sure why because my project is using ember-source 4.x and resolves with `3.13`

https://github.com/josemarluedke/ember-focus-trap/blob/582dc5c9c3fa37a6b4ccb66df459101f859f364e/addon/modifiers/focus-trap.js#L8

I also tried version 1.0.1, but the dependency is not found by the host app (not sure if its a v2 addon thing), even its on addon's dependecies... maybe I should use a blueprint to install ember-focus-trap on the host?

```ts
afterInstall() {
    return this.addAddonToProject('ember-focus-trap', '^1.0.1');
}
```

**Comment by anehx** [comment]
This happens because `dependencySatisfies` needs the requested package to be defined as a `peerDependency` to work. If you update to `v1.0.1` this will be fixed since this addon doesn't use `@embroider/macros` anymore..
