### ISSUE TITLE
Embroider build fails

### ISSUE THREAD

**Issue by anehx** [josemarluedke/ember-focus-trap#59]
Thanks for your work on this addon @josemarluedke ! I was astonished to see that this is already a v2 addon. I'm trying to reach embroider support in a project I'm working on and stumbled upon a weird error with `ember-focus-trap`:

```
ERROR in ./modifiers/focus-trap.js 1:0-67
Module not found: Error: Can't resolve 'ember-focus-trap/modifiers/focus-trap.js' in '$TMPDIR/embroider/ed96c5/packages/workflow/tests/dummy/modifiers'
resolve 'ember-focus-trap/modifiers/focus-trap.js' in '$TMPDIR/embroider/ed96c5/packages/workflow/tests/dummy/modifiers'
  Parsed request is a module
  using description file: $TMPDIR/embroider/ed96c5/packages/workflow/tests/dummy/package.json (relative path: ./modifiers)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      $TMPDIR/embroider/ed96c5/packages/workflow/tests/dummy/modifiers/node_modules doesn't exist or is not a directory
      looking for modules in $TMPDIR/embroider/ed96c5/packages/workflow/tests/dummy/node_modules
        $TMPDIR/embroider/ed96c5/packages/workflow/tests/dummy/node_modules/ember-focus-trap doesn't exist
      $TMPDIR/embroider/ed96c5/packages/workflow/tests/node_modules doesn't exist or is not a directory
      looking for modules in $TMPDIR/embroider/ed96c5/packages/workflow/node_modules
        $TMPDIR/embroider/ed96c5/packages/workflow/node_modules/ember-focus-trap doesn't exist
      $TMPDIR/embroider/ed96c5/packages/node_modules doesn't exist or is not a directory
      looking for modules in $TMPDIR/embroider/ed96c5/node_modules
        $TMPDIR/embroider/ed96c5/node_modules/ember-focus-trap doesn't exist
      $TMPDIR/embroider/node_modules doesn't exist or is not a directory
      $TMPDIR/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./assets/dummy.js 482:13-50
```

https://github.com/projectcaluma/ember-caluma/runs/5642751482

I don't see an obvious reason for this issue, do you see what could be wrong?

**Comment by josemarluedke** [comment]
Hey @anehx! This issue seems a bit strange as the addon is tested against embroider and it is passing. 

I have seen something similar to this issue in other project, and I resolved by making sure I had webpack ^5.67.0 in my deps.

**Comment by josemarluedke** [comment]
I just came across this in one of my projects. It seems that embroider doesn't import correctly a v2 addon file when that is being used in an addon. I solved this issue by adding `ember-focus-trap` as dev dependency of my app.

**Comment by anehx** [comment]
Alright, thanks for the hint! Is there an issue in embroider for this?

**Comment by josemarluedke** [comment]
I'm not sure if there is an issue for this. Could you get that issue going?

**Comment by SanderKnauff** [comment]
I had a similar issue with a pretty clean project as well. Moving ember-focus-trap from `devDependencies` to `dependencies` seems to have fixed it for me.

**Comment by simonihmig** [comment]
I can confirm that behavior you have described here! Reported: https://github.com/embroider-build/embroider/issues/1175

**Comment by betocantu93** [comment]
Yeah, I also faced this and just added instructions in the readme

https://github.com/prysmex/ember-eui/issues/89

**Comment by josemarluedke** [comment]
It seems this issue has been fixed upstreem in emborider: https://github.com/embroider-build/embroider/pull/1278
