### ISSUE TITLE
Missing support for additional elements

### ISSUE THREAD

**Issue by brenner-company** [josemarluedke/ember-focus-trap#71]
First of all, thank you for creating this addon @josemarluedke!

I encountered the following problem last week when using `ember-focus-trap` within the subsequent setup: a modal component (with focus-trap applied) that contains a `ember-power-select` instance which will trigger a dropdown that is added to the body element. 

As the dropdown itself is not located within the focus-trap 'scope', it is not possible to focus the input field inside that dropdown.

This could be fixed by applying `@renderInPlace="true"` to the `ember-power-select` instance, thus rendering the dropdown next to the trigger, but this creates a new issue when the modal has something similar to `overflow-y: auto` applied to.

When looking around for possible solutions, I noticed a related issue within the `focus-trap` repository itself: https://github.com/focus-trap/focus-trap/issues/806. @stefcameron suggests defining additional elements (in my case, the wormhole that contains the dropdown) that will apply the focus-trap (as mentioned here: https://github.com/focus-trap/focus-trap/issues/806#issuecomment-1279630227).

I wanted to apply this solution, but I noticed that, at the moment, there is no support for additional element (only the element where the modifier is placed upon). I tweaked a local version of `ember-focus-trap` a little bit to facilitate this and it seems to work just fine. Is this something that I could add to the addon with a PR?

**Comment by brenner-company** [comment]
FYI, the support for multiple elements (within `focus-trap`) is mentioned here: https://github.com/focus-trap/focus-trap#usage.

> `element` can be:
> 
> - a DOM node (the focus trap itself);
> - a selector string (which will be passed to `document.querySelector()` to find the DOM node); or
> - an array of DOM nodes or selector strings (where the order determines where the focus will go after the last tabbable element of a DOM node/selector is reached).

**Comment by josemarluedke** [comment]
@brenner-company Hey there, I think it makes sense to add a new option that would allow us to pass more elements to it. Feel free to get a PR up for this.

**Comment by brenner-company** [comment]
@josemarluedke I completed my PR at https://github.com/josemarluedke/ember-focus-trap/pull/73. If you have any feedback or questions, feel free to place a comment over there.
