### ISSUE TITLE
Provide convinience import for gjs?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/ember-focus-trap#77]
maybe something like:
```js
import { focusTrap } from 'ember-focus-trap';
```

**Comment by josemarluedke** [comment]
This would be good. We should move to v2 addon and TS as well.

**Comment by NullVoxPopuli** [comment]
is already a v2 addon: https://github.com/josemarluedke/ember-focus-trap/blob/main/packages/ember-focus-trap/package.json#L44

so the most boilerplatey of the 3 things is handled!

**Comment by josemarluedke** [comment]
> is already a v2 addon: https://github.com/josemarluedke/ember-focus-trap/blob/main/packages/ember-focus-trap/package.json#L44

Ohh, it seems past me did it already: https://github.com/josemarluedke/ember-focus-trap/pull/44 LOL
